java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo1 ../matrix/t1
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/t1
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/ash219
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/bcsstk01
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/fs_183_1
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/mbeacxc
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/west0067
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/lp_afiro
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo2 ../matrix/bcsstk16
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo3 ../matrix/bcsstk01
java -cp ../csparsej-1.0.jar edu.emory.mathcs.csparsej.tdouble.demo.Dcs_demo3 ../matrix/bcsstk16